# bpt configuration

[general]
# If a package is requested without the `:<arch>` specified, default to the
# earliest value in the list below which is available in the given context.
#
# `native` indicates packages should be built from source with non-portable
# optimizations tuned specifically for the host system.
# `host` indicates pre-built portable packages suitable for the host system.
# `noarch` indicates pre-built architecture-agnostic portable packages.
# `bbuild` indicates package build definitions rather than binary packages.
# Specific architectures may also be specified, e.g. aarch64, x86_64, etc.
default-archs = noarch, host

# If a package is requested without the `@<pkgver>` specified, the latest
# version is automatically selected both at initial install and upgrade time.
# Otherwise, if `@<pkgver>` is specified, the package is pinned to that
# specific version.
#
# If a `*.bpt` or `*.bbuild` file is specified directly, the setting below
# indicates whether the resulting world entry should pin the `@<pkgver>` or
# allow for automatic upgrades.
pin-direct-pkgver = false


[networking]
# bpt eschews its own networking code in favor of external executables.
#
# Provide utilities which, when `{}` is substituted with an http or https URL,
# fetch and write the corresponding file to stdout.  bpt will utilize the first
# one found in the $PATH.
#
# This uses naive whitespace splitting of arguments.  It does not use shell
# parsing; things like quoting or `&&` do not have special meaning as they may
# in shell contexts.

util = curl -f -L {}
util = wget -O- {}

# Print network utility stderr when calling utility.  This often displays
# download progress and error messages.
print-stderr = false

[build]
# If `bpt` is instructed to source a `.bbuild` or build a package while
# running as root, drop privileges to specified user.
unprivileged-user = bpt

# If `bpt` is instructed to source a `.bbuild` or build a package while
# running as root, drop privileges to specified group.
unprivileged-group = bpt

# Directory in which to store temporary build artifacts
#
# If running on Bedrock Linux, this should be a global directory so that build
# tooling from other strata can access it.
tmp = /tmp

[make-repo]
# When running `bpt make-repo`, create packages and index files for the
# corresponding architectures.
#
# `noarch` indicates architecture agnostic packages should be built and included.
# `host` indicates portable binary packages corresponding to the host system
# should built and included.
# `bbuild` indicates package build definitions should be included in indices.
# Specific architectures may also be specified, e.g. aarch64, x86_64, etc.
archs = noarch, host, bbuild

[cache]
# Upon `bpt update`, clear cached packages over specified age.
# "forever" retains indefinitely, 0 clears immediately.
pkg-max-days = 90

# Upon `bpt update`, clear cached source code over specified age.
# "forever" retains indefinitely, 0 clears immediately.
src-max-days = 90
